# Disable ALSA node suspend-on-idle to avoid broken stereo links
# after standby (especially with Easy Effects).

monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "~alsa_output.*"
      }
      {
        node.name = "~alsa_input.*"
      }
    ]
    actions = {
      update-props = {
        session.suspend-timeout-seconds = 0
      }
    }
  }
]
