workspace = 1, monitor:DP-2
workspace = 2, monitor:DP-2
workspace = 3, monitor:DP-1
workspace = 4, monitor:DP-1
workspace = 5, monitor:DP-1
workspace = 6, monitor:DP-1
workspace = 7, monitor:DP-1
workspace = 8, monitor:DP-1
workspace = 9, monitor:DP-2

cursor {
    no_warps = true
}

windowrule {
    name = to-ws-2
    match:class = ^(Spotify|vesktop)$
    workspace = 2
}

windowrule {
    name = the-floats-by-class
    match:class = ^net\.davidotek\.pupgui2$
    float = true
}

windowrule {
    name = the-floats-by-title
    match:title = ^(Battle.net)$
    float = true
}

windowrule {
    name = world-of-warcraft
    match:title = ^World of Warcraft$
    fullscreen = true
}
